# Generated by Django 5.2.5 on 2025-08-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_code",
                    models.CharField(max_length=20, verbose_name="指标代码"),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="阈值"
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="当前值"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(max_length=20, verbose_name="告警类型"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "已发送"), ("failed", "发送失败")],
                        default="sent",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警记录",
                "verbose_name_plural": "告警记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
