# Generated by Django 5.2.5 on 2025-08-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_code",
                    models.CharField(max_length=20, verbose_name="指标代码"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="指标值"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="时间戳")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "历史指标",
                "verbose_name_plural": "历史指标",
                "indexes": [
                    models.Index(
                        fields=["server", "index_code", "timestamp"],
                        name="metrics_met_server__f90b29_idx",
                    )
                ],
            },
        ),
    ]
