# Generated by Django 5.2.5 on 2025-08-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(max_length=15, unique=True, verbose_name="IP地址"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="服务器名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "服务器",
                "verbose_name_plural": "服务器",
            },
        ),
        migrations.CreateModel(
            name="AlertConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("email", "邮件"),
                            ("feishu", "飞书"),
                            ("dingtalk", "钉钉"),
                        ],
                        max_length=20,
                        verbose_name="告警类型",
                    ),
                ),
                ("config", models.JSONField(verbose_name="配置信息")),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警配置",
                "verbose_name_plural": "告警配置",
            },
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_code",
                    models.CharField(max_length=20, verbose_name="指标代码"),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (">", "大于"),
                            (">=", "大于等于"),
                            ("<", "小于"),
                            ("<=", "小于等于"),
                        ],
                        max_length=10,
                        verbose_name="操作符",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="阈值"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "阈值配置",
                "verbose_name_plural": "阈值配置",
                "unique_together": {("server", "index_code")},
            },
        ),
    ]
